version: "3.8"
services:
  mssql:
    container_name: team-builder-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    #image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin$123
      - MSSQL_PID=Developer
    user: root
    ports:
      - 1433:1433
    volumes:
      - team-builder-sql-volume:/var/opt/mssql

volumes:
  team-builder-sql-volume:
