name: deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:

    env:
      BUILD_OUTPUT_DIR: './TeamBuilder/bin/Release/net8.0/publish'
      REMOTE_DIR: '/wwwroot'
      STATIC_FILES_DIR: '/wwwroot/assets'

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Build Frontend
      run: cd ./TeamBuilder.UI && npm run build:job

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Solution
      run: dotnet restore

    - name: Build Backend
      run: dotnet publish

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Requirements
      run: |
        cd deployment
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute Deployment
      run: |
        cd deployment
        python upload_app_pipeline.py ${{ secrets.SFTP_HOST }} ${{ secrets.SFTP_USER }} ${{ secrets.SFTP_PASS }} "${{ secrets.SFTP_HOST_KEY }}"