name: deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:

    env:
      BUILD_OUTPUT_DIR: './TeamBuilder/bin/Release/net8.0/publish'
      SFTP_HOST: 'site16695.siteasp.net'
      SFTP_USER: 'site16695'
      REMOTE_DIR: '/wwwroot'

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Solution
      run: dotnet restore

    - name: Build
      run: dotnet publish

    - name: Upload Backend to SFTP Server
      uses: wangyucode/sftp-upload-action@v2.0.4
      with:
        host: ${{ env.SFTP_HOST }}
        username: ${{ env.SFTP_USER }}
        password: ${{ secrets.SFTP_PASS }}
        localDir: ${{ env.BUILD_OUTPUT_DIR }}
        remoteDir: ${{ env.REMOTE_DIR }}

    