name: deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Solution
      run: dotnet restore

    - name: Build
      run: dotnet publish

    