name: deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:

    env:
      BUILD_OUTPUT_DIR: './TeamBuilder/bin/Release/net8.0/publish'
      REMOTE_DIR: '/wwwroot'
      STATIC_FILES_DIR: '/wwwroot/assets'

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Build Frontend
      run: cd ./team-builder && npm run build:job

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Solution
      run: dotnet restore

    - name: Build Backend
      run: dotnet publish

    - name: Set Maintenance Mode
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASS }}
        uploads: ./app_offline.htm => /wwwroot/app_offline.htm

    - name: Deploy
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASS }}
        uploads: |
          ${{ env.BUILD_OUTPUT_DIR }} => ${{ env.REMOTE_DIR }}
        delete: 'true'
    