name: deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:

    env:
      BUILD_OUTPUT_DIR: './TeamBuilder/bin/Release/net8.0/publish'
      SFTP_HOST: 'site16695.siteasp.net'
      REMOTE_DIR: '/wwwroot'

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Solution
      run: dotnet restore

    - name: Build
      run: dotnet publish

    - name: Upload Backend to SFTP Server
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ SFTP_HOST }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASS }}
        port: 22
        uploads: |
          ${{ BUILD_OUTPUT_DIR }} => ${{ REMOTE_DIR }}

    